### ISSUE TITLE
NPE is some cases for the collection of metrics

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1018]
```
java.lang.NullPointerException
	at net.nemerosa.ontrack.model.metrics.MetricsExtensionsKt.time(MetricsExtensions.kt:35)
	at net.nemerosa.ontrack.model.metrics.MetricsExtensionsKt.measure(MetricsExtensions.kt:62)
	at net.nemerosa.ontrack.extension.sonarqube.measures.SonarQubeMeasuresCollectionServiceImpl.doCollect(SonarQubeMeasuresCollectionServiceImpl.kt:153)
	at net.nemerosa.ontrack.extension.sonarqube.measures.SonarQubeMeasuresCollectionServiceImpl.collect(SonarQubeMeasuresCollectionServiceImpl.kt:121)
	at net.nemerosa.ontrack.extension.sonarqube.measures.SonarQubeMeasuresCollectionServiceImpl$$EnhancerBySpringCGLIB$$3882c7bc.collect(<generated>)
	at net.nemerosa.ontrack.extension.sonarqube.measures.SonarQubeMeasuresEventListener.onEvent(SonarQubeMeasuresEventListener.kt:34)
```

**Comment by dcoraboeuf** [comment]
Available in 4.2.34
