### ISSUE TITLE
Inaccessible JIRA issues must be ignored in change log

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1226]
When computing a change log, issue authorization issues (access issue should be logged, but the change log should ignore the problem).

```
org.springframework.web.client.HttpClientErrorException$Forbidden: 403 : "{"errorMessages":["You do not have the permission to see the specified issue."],"errors":{}}"
at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:109)
at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)
at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:825)
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:783)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717)
at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:340)
at net.nemerosa.ontrack.extension.jira.client.JIRAClientImpl.fetchIssue(JIRAClientImpl.kt:184)
at net.nemerosa.ontrack.extension.jira.client.JIRAClientImpl.getIssue(JIRAClientImpl.kt:30)
at net.nemerosa.ontrack.extension.jira.JIRAServiceExtension.getIssue(JIRAServiceExtension.kt:115)
at net.nemerosa.ontrack.extension.jira.JIRAServiceExtension.getIssue(JIRAServiceExtension.kt:64)
at net.nemerosa.ontrack.extension.issues.model.ConfiguredIssueService.getIssue(ConfiguredIssueService.java:34)
at net.nemerosa.ontrack.extension.scm.changelog.SCMChangeLogServiceImpl.computeChangeLog(SCMChangeLogServiceImpl.kt:93)
at net.nemerosa.ontrack.extension.scm.changelog.SCMChangeLogServiceImpl.getChangeLog$suspendImpl(SCMChangeLogServiceImpl.kt:51)
at net.nemerosa.ontrack.extension.scm.changelog.SCMChangeLogServiceImpl.getChangeLog(SCMChangeLogServiceImpl.kt)
at net.nemerosa.ontrack.extension.scm.graphql.GQLRootQuerySCMChangeLog$getFieldDefinition$1$1.invokeSuspend(GQLRootQuerySCMChangeLog.kt:47)
```

**Comment by dcoraboeuf** [comment]
Available in 4.8.37
