### ISSUE TITLE
Error in datadog: Uncaught error on flushing events (for Elastic Search)

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1284]
```
java.lang.NoClassDefFoundError: jakarta/json/stream/JsonParser$Event
	at co.elastic.clients.elasticsearch.core.BulkResponse.<clinit>(BulkResponse.java:239)
	at co.elastic.clients.elasticsearch.core.BulkRequest.<clinit>(BulkRequest.java:621)
	at co.elastic.clients.elasticsearch.core.BulkRequest$Builder.build(BulkRequest.java:533)
	at net.nemerosa.ontrack.extension.elastic.metrics.DefaultElasticMetricsClient.flushing(DefaultElasticMetricsClient.kt:217)
	at net.nemerosa.ontrack.extension.elastic.metrics.DefaultElasticMetricsClient.access$flushing(DefaultElasticMetricsClient.kt:36)
	at net.nemerosa.ontrack.extension.elastic.metrics.DefaultElasticMetricsClient$flushEvents$2.invokeSuspend(DefaultElasticMetricsClient.kt:183)
        ...
	at net.nemerosa.ontrack.extension.elastic.metrics.DefaultElasticMetricsClient.flushEvents(DefaultElasticMetricsClient.kt:176)
```

**Comment by dcoraboeuf** [comment]
Aligning first the versions of Spring Boot & Elastic Search - https://github.com/nemerosa/ontrack/issues/1285
