### ISSUE TITLE
Exception when deleting a promotion run

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#1302]
* create a promotion on a build
* delete this promotion
* some notifications listen to this event and the following exception is generated:

```
2024-06-19 11:58:41.462 DEBUG 1 --- [io-8080-exec-31] n.n.o.s.events.EventListenerServiceImpl : Event listener AutoPromotionEventListener: 0ms
2024-06-19 11:58:41.463 DEBUG 1 --- [io-8080-exec-31] n.n.o.s.events.EventListenerServiceImpl : Event listener EventSubscriptionsListener: 1ms
2024-06-19 11:58:41.463 DEBUG 1 --- [io-8080-exec-31] n.n.o.s.events.EventListenerServiceImpl : Event listener LicenseControlListener: 0ms
2024-06-19 11:58:41.463 DEBUG 1 --- [io-8080-exec-31] n.n.o.s.events.EventListenerServiceImpl : Event listener ConfigurationPropertyCleanupListener: 0ms
2024-06-19 11:58:41.482 ERROR 1 --- [ching.default-1] n.n.o.m.support.ApplicationLogService : [ERROR] name=notifications-dispatching-error,authentication=anonymous,timestamp=2024-06-19T11:58:41.4817,
Stacktrace: net.nemerosa.ontrack.model.exceptions.PromotionRunNotFoundException: Promotion run ID not found: 4171
at net.nemerosa.ontrack.repository.StructureJdbcRepository.getPromotionRun(StructureJdbcRepository.java:600)
at net.nemerosa.ontrack.repository.StructureJdbcRepository$$FastClassBySpringCGLIB$$bf08d5d9.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
at net.nemerosa.ontrack.repository.StructureJdbcRepository$$EnhancerBySpringCGLIB$$59a161b2.getPromotionRun(<generated>)
at net.nemerosa.ontrack.service.StructureServiceImpl.getPromotionRun(StructureServiceImpl.kt:840)
at net.nemerosa.ontrack.service.StructureServiceImpl$$FastClassBySpringCGLIB$$da6c1020.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
at net.nemerosa.ontrack.service.StructureServiceImpl$$EnhancerBySpringCGLIB$$8fe45857.getPromotionRun(<generated>)
at net.nemerosa.ontrack.model.structure.ProjectEntityType.lambda$getEntityFn$1(ProjectEntityType.java:41)
at net.nemerosa.ontrack.extension.notifications.listener.AsyncEventListeningQueueEvent.toEvent(AsyncEventListeningQueueEvent.kt:37)
at net.nemerosa.ontrack.extension.notifications.listener.AsyncEventListeningQueueListener.onMessage$lambda$0(AsyncEventListeningQueueListener.kt:61)
```

A "promotion run deleted" event should not try to access the deleted promotion run.

**Comment by dcoraboeuf** [comment]
Available in 4.8.76
