### ISSUE TITLE
Error on Search

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#245]
When executing a search, the following error sometimes occurs:

```
org.springframework.transaction.UnexpectedRollbackException: Transaction rolled back because it has been marked as rollback-only
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:720)
...
	at net.nemerosa.ontrack.service.SearchServiceImpl$$EnhancerBySpringCGLIB$$8a40be25.search(<generated>)
	at net.nemerosa.ontrack.boot.ui.SearchController.search(SearchController.java:29)
```

**Comment by dcoraboeuf** [comment]
To reproduce:

1. launch in Acceptance mode
1. run the `ACCDSL` test suite
1. run the `ACCSearch` test suite
