### ISSUE TITLE
Timeout connection to github appliance using docker nemerosa/ontrack:2.26.3

### ISSUE THREAD

**Issue by jonbrohauge** [nemerosa/ontrack#464]
After firing up ontrack in a Docker container and logging in using the default login credentials I tried to add a GitHub configuration. It failed with the error message: ```Error while accessing GitHub: java.net.ConnectException: Connection timed out```. 

I have logged into the container and added all our ssl-certificates to make sure that certificates are not the issue. This has been confirmed by executing ```curl -k https://github.MyDomainName.local``` and ```curl https://github.MyDomainName.local``` and comparing the results. They are the same. 

Setting up an Artifactory configuration having it point to the url: ```http://artifactory.MyDomainName.local``` worked like a charm. 

Setting up a Git configuration to a specific repository ```https://github.MyDomainName.local/MyOrganization/MyRepository.git``` worked like a charm after adding the certificates.

As a last resort, I added http_proxy, https_proxy and no_proxy when bashing into the running container.

Trying to set up a GitHub configuration leaving out the URL, thus having it point to default ```https://github.com``` times out as well.

**Comment by dcoraboeuf** [comment]
It happens that there is (or was) a major GitHub outage: https://status.github.com/

Can you try again?

**Comment by fumblingwithit** [comment]
The important point is I could not connect to our internal GitHub installation.

**Comment by dcoraboeuf** [comment]
Can you post the complete stack trace? The one leading to `java.net.ConnectException: Connection timed out` ?

**Comment by fumblingwithit** [comment]
![image](https://cloud.githubusercontent.com/assets/9496731/20362729/de043bac-ac3c-11e6-9e32-c0d0453017ae.png)

output from /var/ontrack/data/log/ontrack.log
```
2016-11-16 19:29:43.334 DEBUG 7 --- [job-9] net.nemerosa.ontrack.job.JobScheduler    : [job][core][orchestrator][collection] Running now
2016-11-16 19:29:43.335 DEBUG 7 --- [job-9] net.nemerosa.ontrack.job.JobScheduler    : [job][core][orchestrator][collection] Ran in 1 ms
2016-11-16 19:37:22.081 DEBUG 7 --- [http-nio-8080-exec-2] n.n.o.e.g.client.OntrackGitHubClient     : [github] Getting repository list
2016-11-16 19:39:43.334 DEBUG 7 --- [job-10] net.nemerosa.ontrack.job.JobScheduler    : [job][core][orchestrator][collection] Trying to run now - forced = false
2016-11-16 19:39:43.334 DEBUG 7 --- [job-10] net.nemerosa.ontrack.job.JobScheduler    : [job][core][orchestrator][collection] Running now
```

**Comment by dcoraboeuf** [comment]
Indeed, this won't help. When I validate the settings, I do not log any exception since this is not an operational error, and I just show the error message. But in your case, this is definitely not enough to understand the reason why you cannot connect.

I'll log the error and release a 2.26.4. Will it be OK for you to test?

I've never seen this error before and I've been using GitHub (cloud) and BitBucket (cloud & server)...

**Comment by dcoraboeuf** [comment]
Hi,

Can you try to reproduce the issue with the newly released 2.26.4. No fix planned, but at least more traces.

Thanks,
Damien.

**Comment by fumblingwithit** [comment]
Output from the log file. Just cut the top of the stack trace. I can dump the complete log-file to you via PM, if you want.
```
2016-11-17 08:34:14.175 DEBUG 7 --- [http-nio-8080-exec-6] n.n.o.e.g.client.OntrackGitHubClient     : [github] Getting repository list
2016-11-17 08:36:21.505 ERROR 7 --- [http-nio-8080-exec-6] n.n.o.m.support.ApplicationLogService    : [ERROR] name=github,authentication=admin,timestamp=2016-11-17T08:36:21.498,github-config-name=githubEE,github-config-url=https://github.MyDomainName.local/

net.nemerosa.ontrack.extension.github.client.OntrackGitHubClientException: Error while accessing GitHub: java.net.ConnectException: Connection timed out
        at net.nemerosa.ontrack.extension.github.client.DefaultOntrackGitHubClient.getRepositories(DefaultOntrackGitHubClient.java:45)
        at net.nemerosa.ontrack.extension.github.service.GitHubConfigurationServiceImpl.validate(GitHubConfigurationServiceImpl.java:37)
        at net.nemerosa.ontrack.extension.github.service.GitHubConfigurationServiceImpl.validate(GitHubConfigurationServiceImpl.java:17)
        at net.nemerosa.ontrack.extension.support.AbstractConfigurationService.test(AbstractConfigurationService.java:141)
        at net.nemerosa.ontrack.extension.github.GitHubController.testConfiguration(GitHubController.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
```

**Comment by dcoraboeuf** [comment]
Yes please, I'd like to have the whole stack. You can post it as PM on Twitter: `@DamienCoraboeuf`

**Comment by fumblingwithit** [comment]
You need to follow me before I can send a PM through Twitter.
``` @fumblingwithit ```

**Comment by dcoraboeuf** [comment]
Done :)

**Comment by fumblingwithit** [comment]
Exception sent. Enjoy ;-)

**Comment by dcoraboeuf** [comment]
I did not find anything obvious. I do see why the Java code should have a timeout when it works fine with Curl.

**Comment by fumblingwithit** [comment]
Could you elaborate? Is there anything I can do?

**Comment by dcoraboeuf** [comment]
This looks like a very low level error and I didn't see anything related in the code.

Since it is working using Curl in your Ontrack container, I assume there is something wrong at Java level. So yes, I'm a bit stuck here :(

**Comment by fumblingwithit** [comment]
[Thinking out loud]: Maybe I should try to add our certificates to the java-key using keytool?

**Comment by dcoraboeuf** [comment]
If the error was due to the certificates, you'd have a corresponding exception, not a timeout. But yes, normally, you should install those certificates using the `keytool`, like described at http://nemerosa.github.io/ontrack/release/latest/doc/index.html#appendix-certificates

**Comment by fumblingwithit** [comment]
argh! typo in default password... Embarrassing. I'll add them and re-test, just to be sure that's not the issue ;-)

**Comment by dcoraboeuf** [comment]
I'm the king of the typo myself, so I do not blame you :)

**Comment by fumblingwithit** [comment]
Anyway... Just to verify. Still time out.

**Comment by dcoraboeuf** [comment]
Hi Jon,

Still stuck with this issue?

I was not able to reproduce it, but I do not have GitHub enterprise...
