### ISSUE TITLE
Regression: AbstractMethodError on ResourceDecorationContributor implementations

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#491]
After an upgrade to 2.29.x, when an extension implements the `ResourceDecorationContributor` class, calls to its `applyTo` method raise an `AbstractMethodError` exception:

```
java.lang.AbstractMethodError: net.nemerosa.ontrack.extension.coastguard.BranchCoastguardResourceDecorationContributor.applyTo(Ljava/lang/Class;)Z
	at net.nemerosa.ontrack.ui.resource.ResourceDecorationContributorServiceImpl.lambda$getLinkDefinitions$0(ResourceDecorationContributorServiceImpl.java:27)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at net.nemerosa.ontrack.ui.resource.ResourceDecorationContributorServiceImpl.getLinkDefinitions(ResourceDecorationContributorServiceImpl.java:26)
	at net.nemerosa.ontrack.boot.resources.ProjectResourceDecorator.getLinkDefinitions(ProjectResourceDecorator.java:101)
```

The error is _not_ detected at compilation time.

**Comment by dcoraboeuf** [comment]
Simplification of the method signature does not change a thing. Still the same error on the abstract method error.

**Comment by dcoraboeuf** [comment]
It was not an issue with the code itself, but with some corruption of the local Docker images in the target deployment host. I've removed all images and restarted the deployment. The problem just disappeared.
