### ISSUE TITLE
Migration to Spring Boot 1.5

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#492]
See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes

**Comment by dcoraboeuf** [comment]
Could not start the application in Intellij after the upgrade.

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
	at net.nemerosa.ontrack.boot.Application.main(Application.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```
