### ISSUE TITLE
BitBucket configuration - do not fail on empty issue configuration

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#494]
When running:

```groovy
project.config {
    stash 'MyStash', 'PRJ', 'repo'
}
```

without specifying the indexation interval not the issue configuration, this causes an issue when the configuration is parsed back:

```
net.nemerosa.ontrack.extension.issues.model.IssueServiceConfigurationIdentifierFormatException: Wrong format for an issue service configuration ID: ""
	at net.nemerosa.ontrack.extension.issues.model.IssueServiceConfigurationIdentifier.parse(IssueServiceConfigurationIdentifier.java:28)
	at net.nemerosa.ontrack.extension.issues.support.IssueServiceRegistryImpl.getConfiguredIssueService(IssueServiceRegistryImpl.java:65)
	at net.nemerosa.ontrack.extension.stash.property.StashConfigurator.getConfiguredIssueService(StashConfigurator.java:41)
	at net.nemerosa.ontrack.extension.stash.property.StashConfigurator.getGitConfiguration(StashConfigurator.java:36)
	at net.nemerosa.ontrack.extension.stash.property.StashConfigurator$$Lambda$151/1137515698.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at net.nemerosa.ontrack.extension.stash.property.StashConfigurator.getConfiguration(StashConfigurator.java:30)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl.lambda$getProjectConfiguration$29(GitServiceImpl.java:711)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl$$Lambda$144/1079316302.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl.getProjectConfiguration(GitServiceImpl.java:714)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl$$FastClassBySpringCGLIB$$883c1acc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:280)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl$$EnhancerBySpringCGLIB$$d1eca8f6.getProjectConfiguration(<generated>)
	at net.nemerosa.ontrack.extension.git.GitProjectResourceDecorationContributor.contribute(GitProjectResourceDecorationContributor.java:29)
	at net.nemerosa.ontrack.ui.resource.ResourceDecorationContributorServiceImpl.lambda$contribute$1(ResourceDecorationContributorServiceImpl.java:22)
	at net.nemerosa.ontrack.ui.resource.ResourceDecorationContributorServiceImpl$$Lambda$330/1730138674.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:600)
	at net.nemerosa.ontrack.ui.resource.ResourceDecorationContributorServiceImpl.contribute(ResourceDecorationContributorServiceImpl.java:20)
```

The parser must accept an empty string as being not filled in.

**Comment by dcoraboeuf** [comment]
Regression for #473

**Comment by dcoraboeuf** [comment]
This is actually linked to the more general issue at #360, where _empty strings_ are passed using actually `""`.

**Comment by dcoraboeuf** [comment]
Ultimately a Jenkins issue - see jenkinsci/ontrack-plugin#16
