### ISSUE TITLE
Cannot update a project any longer

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#731]
1. Create a project
2. Got to its page
3. Hit the "Update project" button

Call is rejected because of:

```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method net.nemerosa.ontrack.model.form.Form.description, parameter value
	at net.nemerosa.ontrack.model.form.Form.description(Form.kt)
	at net.nemerosa.ontrack.model.structure.Project.asForm(Project.java:63)
	at net.nemerosa.ontrack.boot.ui.ProjectController.saveProjectForm(ProjectController.java:114)
```

**Comment by dcoraboeuf** [comment]
Still not fixed after CORS update

**Comment by dcoraboeuf** [comment]
Duplicates #730
