### ISSUE TITLE
Git commit search indexation failing in some cases

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#737]
```
org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: no requests added;
	at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:26)
	at org.elasticsearch.action.bulk.BulkRequest.validate(BulkRequest.java:382)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1480)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1454)
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:497)
	at net.nemerosa.ontrack.extension.elastic.ElasticSearchIndexService.batchSearchIndex(ElasticSearchIndexService.kt:199)
	at net.nemerosa.ontrack.extension.elastic.ElasticSearchIndexService$$FastClassBySpringCGLIB$$4499f913.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at net.nemerosa.ontrack.extension.elastic.ElasticSearchIndexService$$EnhancerBySpringCGLIB$$da7dd4b.batchSearchIndex(<generated>)
	at net.nemerosa.ontrack.extension.git.GitIssueSearchExtension.processIssueKeys(GitIssueSearchExtension.kt:128)
	at net.nemerosa.ontrack.extension.git.GitCommitSearchExtension$indexAll$1.accept(GitCommitSearchExtension.kt:119)
	at net.nemerosa.ontrack.extension.git.GitCommitSearchExtension$indexAll$1.accept(GitCommitSearchExtension.kt:25)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl.forEachConfiguredProject(GitServiceImpl.kt:74)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl$$FastClassBySpringCGLIB$$883c1acc.invoke(<generated>)
```

**Comment by dcoraboeuf** [comment]
Not an issue - was looking at a previous release
