### ISSUE TITLE
Migrating to 3.38.7 version: Facing an issue in migration

### ISSUE THREAD

**Issue by raj333921** [nemerosa/ontrack#801]
Hi,
I am able to start my containers and able to run migration steps, While running migration I am recieving an error 020-07-06 18:04:37.133  INFO 57788 --- [           main] n.n.o.migration.postgresql.Migration     : BUILD_LINKS count = 0...
2020-07-06 18:04:37.134  INFO 57788 --- [           main] n.n.o.migration.postgresql.Migration     : Migrating RUN_INFO...
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT * FROM RUN_INFO]; nested exception is org.h2.jdbc.JdbcSQLException: Table "RUN_INFO" not found; SQL statement:
SELECT * FROM RUN_INFO [42102-196]
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:230)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:655)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:690)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:717)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:767)
        at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:192)
        at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForList(NamedParameterJdbcTemplate.java:264)
        at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForList(NamedParameterJdbcTemplate.java:271)
        at net.nemerosa.ontrack.migration.postgresql.Migration.simpleMigration(Migration.kt:433)
        at net.nemerosa.ontrack.migration.postgresql.Migration.access$simpleMigration(Migration.kt:19)
        at net.nemerosa.ontrack.migration.postgresql.Migration$copy$1.invoke(Migration.kt:422)
        at net.nemerosa.ontrack.migration.postgresql.Migration$copy$1.invoke(Migration.kt:19)
        at net.nemerosa.ontrack.migration.postgresql.Migration$tx$1.doInTransactionWithoutResult(Migration.kt:396)
        at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at net.nemerosa.ontrack.migration.postgresql.Migration.tx(Migration.kt:393)
        at net.nemerosa.ontrack.migration.postgresql.Migration.copy(Migration.kt:421)
        at net.nemerosa.ontrack.migration.postgresql.Migration.run(Migration.kt:130)
        at net.nemerosa.ontrack.migration.postgresql.MigrationTool.main(MigrationTool.java:41)
        ... 8 more
Caused by: org.h2.jdbc.JdbcSQLException: Table "RUN_INFO" not found; SQL statement:
SELECT * FROM RUN_INFO [42102-196]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.command.Parser.readTableOrView(Parser.java:5552)
        at org.h2.command.Parser.readTableFilter(Parser.java:1266)
        at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1946)
        at org.h2.command.Parser.parseSelectSimple(Parser.java:2095)
        at org.h2.command.Parser.parseSelectSub(Parser.java:1940)
        at org.h2.command.Parser.parseSelectUnion(Parser.java:1755)
        at org.h2.command.Parser.parseSelect(Parser.java:1743)
        at org.h2.command.Parser.parsePrepared(Parser.java:449)
        at org.h2.command.Parser.parse(Parser.java:321)
        at org.h2.command.Parser.parse(Parser.java:293)
        at org.h2.command.Parser.prepareCommand(Parser.java:258)
        at org.h2.engine.Session.prepareLocal(Session.java:578)
        at org.h2.engine.Session.prepareCommand(Session.java:519)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
        at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
        at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:75)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
        at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
        at com.sun.proxy.$Proxy64.prepareStatement(Unknown Source)
        at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:238)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
        ... 25 more

**Comment by raj333921** [comment]
[logs.txt](https://github.com/nemerosa/ontrack/files/4880108/logs.txt)

**Comment by raj333921** [comment]
Sorry Damien, I was not looking right data.mv.db path. After investigating i found it and closing an issue
