### ISSUE TITLE
Ontrack Migration: Getting an error while doing migration

### ISSUE THREAD

**Issue by raj333921** [nemerosa/ontrack#802]
I am keep receiving similar error while i am doing migration from H2 to Postgres using ontrack-migration jar.
This is causing for production data. Every time i run command java -jar its giving same exception but with Key(ID) is different.

I am using a check to clear my db using application.properties and i connected to h2 and checking there it was only 1 record exists , If i am loading repetition data its no error becuase ENTITY_DATA is loading fast.

Or should i go with own migration ? Please help me out.

    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [INSERT INTO ENTITY_DATA(ID,NAME,PROJECT,BRANCH,PROMOTION_LEVEL,VALIDATION_STAMP,BUILD,PROMOTION_RUN,VALIDATION_RUN,JSON_VALUE) SELECT ID,NAME,PROJECT,BRANCH,PROMOTION_LEVEL,VALIDATION_STAMP,BUILD,PROMOTION_RUN,VALIDATION_RUN,JSON_VALUE FROM TMP_ENTITY_DATA]; ERROR: duplicate key value violates unique constraint "entity_data_pkey"
  Detail: Key (id)=(5375) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "entity_data_pkey"
  Detail: **Key (id)=(5375) already exists.**
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:238)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:419)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:445)
        at net.nemerosa.ontrack.migration.postgresql.Migration$copyWithTmp$2.invoke(Migration.kt:351)
        at net.nemerosa.ontrack.migration.postgresql.Migration$copyWithTmp$2.invoke(Migration.kt:19)
        at net.nemerosa.ontrack.migration.postgresql.Migration$tx$1.doInTransactionWithoutResult(Migration.kt:396)
        at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)

**Comment by dcoraboeuf** [comment]
Hi @raj333921 ,

Can you mention the version you migrate from (2.x) and the version of the migration tool (3.x)?

What could also help in fixing this issue is the rest of the stacktrace ; I suppose the one you posted has been truncated and we don't see the ontrack part, only the low level stack in Spring / Postgres. Can you post a more complete stacktrace?

Thanks,
Damien

PS: being right now in holidays, I won't be able to look at the issue right now, but possibly next week.

**Comment by raj333921** [comment]
Migration Version : 3.38.7
Old version: 2.35.2
[logs.txt](https://github.com/nemerosa/ontrack/files/4923564/logs.txt)

Application Properties:
ontrack.migration.skip-events=false
ontrack.migration.cleanup=true
ontrack.migration.postgresql.url=jdbc:postgresql://172.18.0.3:5432/ontrack
ontrack.migration.h2.url=jdbc:h2:./data;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DEFRAG_ALWAYS=TRUE

Note: I am migrating data from Production server where data is 96GB

**Comment by dcoraboeuf** [comment]
Any reason not to target the latest version (3.41.x) ?

**Comment by dcoraboeuf** [comment]
I had a look at the migration scenario and at what is actually happening.

It looks to me like some kind of corruption of index in the H2 database since the `ENTITY_DATA.ID` is a primary key and should therefore be unique.

It's difficult to assert the situation without having access to the database in the first place :( If possible, could you intercept the migration process (by running the code from an IDE for example) and stop when `TMP_ENTITY_DATA` is filled, and check for duplicate IDs)?

**Comment by raj333921** [comment]
We are on 2.35.x and now moving to this new version ... If that is not an
issue I can check it on Monday and post you update

**Comment by raj333921** [comment]
Because of spring boot & kotlin upgrade i am getting compilation issues because some are depricated !!
import org.springframework.boot.actuate.metrics.Metric
import org.springframework.boot.actuate.metrics.CounterService

import kotlinx.coroutines.experimental.delay

**Comment by dcoraboeuf** [comment]
Yes, many things will have changed between 2.x and 3.x.

I assume that you've defined an extension to Ontrack?

**Comment by dcoraboeuf** [comment]
Also: feel free to join the channel at https://gitter.im/nemerosa/ontrack - it's easier for discussions
