### ISSUE TITLE
Cannot load projects because of old entities not having a signature

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#825]
```
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method net.nemerosa.ontrack.model.structure.Signature$Companion.of, parameter dateTime
	at net.nemerosa.ontrack.model.structure.Signature$Companion.of(Signature.kt)
	at net.nemerosa.ontrack.model.structure.Signature.of(Signature.kt)
	at net.nemerosa.ontrack.repository.support.AbstractJdbcRepository.readSignature(AbstractJdbcRepository.java:115)
	at net.nemerosa.ontrack.repository.support.AbstractJdbcRepository.readSignature(AbstractJdbcRepository.java:111)
	at net.nemerosa.ontrack.repository.StructureJdbcRepository.toProject(StructureJdbcRepository.java:1375)
	at net.nemerosa.ontrack.repository.StructureJdbcRepository.lambda$getProjectList$0(StructureJdbcRepository.java:67)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:94)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:61)
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:440)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:452)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:462)
	at net.nemerosa.ontrack.repository.StructureJdbcRepository.getProjectList(StructureJdbcRepository.java:65)
```

**Comment by dcoraboeuf** [comment]
Faulty record updated in the database
