### ISSUE TITLE
NPE with getting old projects in V4

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#831]
From the home page:

```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method net.nemerosa.ontrack.model.structure.Signature$Companion.of, parameter dateTime
	at net.nemerosa.ontrack.model.structure.Signature$Companion.of(Signature.kt)
	at net.nemerosa.ontrack.model.structure.Signature.of(Signature.kt)
	at net.nemerosa.ontrack.repository.support.AbstractJdbcRepository.readSignature(AbstractJdbcRepository.java:115)
	at net.nemerosa.ontrack.repository.support.AbstractJdbcRepository.readSignature(AbstractJdbcRepository.java:111)
	at net.nemerosa.ontrack.repository.StructureJdbcRepository.toProject(StructureJdbcRepository.java:1379)
```

Some old projects have a wrong signature.

**Comment by dcoraboeuf** [comment]
Solved in the database itself. Not worth a fix.
