### ISSUE TITLE
Getting a branch as a PR should not fail when GitHub cannot be reached

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#882]
`GitServiceImpl.getBranchAsPullRequest` should not fail when we cannot connect to GitHub.

```
Stacktrace: org.springframework.cache.Cache$ValueRetrievalException: Value for key '1760' could not be loaded using 'net.nemerosa.ontrack.extension.git.service.GitServiceImpl$getBranchAsPullRequest$3@53cfabaa'
	at org.springframework.cache.caffeine.CaffeineCache$LoadFunction.apply(CaffeineCache.java:171)
	at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:139)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2346)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2344)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2327)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at org.springframework.cache.caffeine.CaffeineCache.get(CaffeineCache.java:90)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl.getBranchAsPullRequest(GitServiceImpl.kt:698)
Caused by: net.nemerosa.ontrack.extension.github.client.OntrackGitHubClientException: Error while accessing GitHub: org.eclipse.egit.github.core.client.RequestException: Bad credentials (401)
	at net.nemerosa.ontrack.extension.github.client.DefaultOntrackGitHubClient.getPullRequest(DefaultOntrackGitHubClient.kt:220)
	at net.nemerosa.ontrack.extension.github.property.GitHubConfigurator.getPullRequest(GitHubConfigurator.kt:37)
```

**Comment by dcoraboeuf** [comment]
Available in 4.0.17
