### ISSUE TITLE
GitHub issue change log failing when some issues have no description at all

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#896]
```
java.lang.NullPointerException: issue.bodyText must not be null
	at net.nemerosa.ontrack.extension.github.client.DefaultOntrackGitHubClient.getIssue(DefaultOntrackGitHubClient.kt:119)
	at net.nemerosa.ontrack.extension.github.GitHubIssueServiceExtension.getIssue(GitHubIssueServiceExtension.java:129)
	at net.nemerosa.ontrack.extension.issues.model.ConfiguredIssueService.getIssue(ConfiguredIssueService.java:35)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl.getChangeLogIssues(GitServiceImpl.kt:299)
```

**Comment by dcoraboeuf** [comment]
Available in 4.0.26
