### ISSUE TITLE
Do not fail computation when one indicator fails

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#902]
Among the collection of all the indicator computations run by one job, it might happen that one computation in particular fails. The rest of the computation should go on, and the job should not fail (the errors should be logged though):

```
net.nemerosa.ontrack.git.exceptions.GitRepositoryAPIException: Git API exception on https://github.com/xxxx/yyyy.git
	at net.nemerosa.ontrack.git.support.GitRepositoryClientImpl.fetch(GitRepositoryClientImpl.kt:222)
	at net.nemerosa.ontrack.git.support.GitRepositoryClientImpl.sync(GitRepositoryClientImpl.kt:201)
	at net.nemerosa.ontrack.git.support.GitRepositoryClientImpl.download(GitRepositoryClientImpl.kt:483)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl$download$2.invoke(GitServiceImpl.kt:416)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl$download$2.invoke(GitServiceImpl.kt:53)
	at net.nemerosa.ontrack.tx.TransactionService$DefaultImpls.doInTransaction(TransactionService.kt:12)
	at net.nemerosa.ontrack.tx.DefaultTransactionService.doInTransaction(DefaultTransactionService.kt:10)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl.download(GitServiceImpl.kt:411)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl$$FastClassBySpringCGLIB$$883c1acc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at net.nemerosa.ontrack.extension.git.service.GitServiceImpl$$EnhancerBySpringCGLIB$$75990240.download(<generated>)
	at net.nemerosa.ontrack.extension.jenkins.indicator.JenkinsPipelineLibraryIndicatorComputer.computeSCMIndicators(JenkinsPipelineLibraryIndicatorComputer.kt:37)
	at net.nemerosa.ontrack.extension.scm.indicator.AbstractSCMIndicatorComputer.computeIndicators(AbstractSCMIndicatorComputer.kt:44)
	at net.nemerosa.ontrack.extension.indicators.computing.IndicatorComputingServiceImpl.compute(IndicatorComputingServiceImpl.kt:22)
```

**Comment by dcoraboeuf** [comment]
Available in 4.0.32
