### ISSUE TITLE
Some GitHub check indicators cannot be saved because of constraint errors

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#903]
```
org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [INSERT INTO STORAGE(STORE, NAME, DATA) VALUES (?, ?, CAST(? AS JSONB))]; ERROR: duplicate key value violates unique constraint "storage_pk"
  Detail: Key (store, name)=(net.nemerosa.ontrack.extension.indicators.model.IndicatorCategory, github-compliance-settings) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "storage_pk"
  Detail: Key (store, name)=(net.nemerosa.ontrack.extension.indicators.model.IndicatorCategory, github-compliance-settings) already exists.
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:981)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:328)
	at net.nemerosa.ontrack.repository.StorageJdbcRepository.storeJson(StorageJdbcRepository.java:53)
	at net.nemerosa.ontrack.repository.StorageJdbcRepository$$FastClassBySpringCGLIB$$d5e84121.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at net.nemerosa.ontrack.repository.StorageJdbcRepository$$EnhancerBySpringCGLIB$$49e06518.storeJson(<generated>)
	at net.nemerosa.ontrack.service.support.StorageServiceImpl.storeJson(StorageServiceImpl.java:27)
	at net.nemerosa.ontrack.model.support.StorageService.store(StorageService.java:56)
	at net.nemerosa.ontrack.model.support.StorageService$$FastClassBySpringCGLIB$$c7535ba3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at net.nemerosa.ontrack.service.support.StorageServiceImpl$$EnhancerBySpringCGLIB$$d531f901.store(<generated>)
	at net.nemerosa.ontrack.extension.indicators.model.IndicatorCategoryServiceImpl.updateCategory(IndicatorCategoryServiceImpl.kt:43)
	at net.nemerosa.ontrack.extension.indicators.model.IndicatorCategoryServiceImpl$$FastClassBySpringCGLIB$$3a4610c3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at net.nemerosa.ontrack.extension.indicators.model.IndicatorCategoryServiceImpl$$EnhancerBySpringCGLIB$$5e28d685.updateCategory(<generated>)
	at net.nemerosa.ontrack.extension.indicators.computing.IndicatorComputingServiceImpl$prepareTypes$1.replaceTargetItem(IndicatorComputingServiceImpl.kt:79)
	at net.nemerosa.ontrack.extension.indicators.computing.IndicatorComputingServiceImpl$prepareTypes$1.replaceTargetItem(IndicatorComputingServiceImpl.kt:53)
	at net.nemerosa.ontrack.model.structure.SyncPolicy.sync(SyncPolicy.java:95)
	at net.nemerosa.ontrack.extension.indicators.computing.IndicatorComputingServiceImpl.prepareTypes(IndicatorComputingServiceImpl.kt:53)
	at net.nemerosa.ontrack.extension.indicators.computing.IndicatorComputingServiceImpl.compute(IndicatorComputingServiceImpl.kt:25)
	at net.nemerosa.ontrack.extension.indicators.computing.IndicatorComputingServiceImpl$$FastClassBySpringCGLIB$$af1433c0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at net.nemerosa.ontrack.extension.indicators.computing.IndicatorComputingServiceImpl$$EnhancerBySpringCGLIB$$362e859c.compute(<generated>)
	at net.nemerosa.ontrack.extension.indicators.computing.IndicatorComputingJobs$compute$1.invoke(IndicatorComputingJobs.kt:90)
	at net.nemerosa.ontrack.extension.indicators.computing.IndicatorComputingJobs$compute$1.invoke(IndicatorComputingJobs.kt:14)
	at net.nemerosa.ontrack.model.support.MeterRegistryExtensionsKt$sam$java_util_function_Supplier$0.get(MeterRegistryExtensions.kt)
	at io.micrometer.core.instrument.AbstractTimer.record(AbstractTimer.java:149)
	at net.nemerosa.ontrack.model.support.MeterRegistryExtensionsKt.time(MeterRegistryExtensions.kt:21)
	at net.nemerosa.ontrack.extension.indicators.computing.IndicatorComputingJobs.compute(IndicatorComputingJobs.kt:85)
```

**Comment by dcoraboeuf** [comment]
Available in 4.0.32
