### ISSUE TITLE
Cannot list GitHub configurations

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#914]
Even when no app is defined, the GitHub configurations cannot be accessed because of:

```
java.lang.IllegalArgumentException: Illegal base64 character 5f
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:743)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:535)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:558)
	at net.nemerosa.ontrack.service.security.CryptoConfidentialKey.decrypt(CryptoConfidentialKey.kt:80)
	at net.nemerosa.ontrack.service.security.EncryptionServiceImpl.decrypt(EncryptionServiceImpl.kt:27)
	at net.nemerosa.ontrack.extension.support.AbstractConfigurationService$decrypt$1.invoke(AbstractConfigurationService.kt:168)
	at net.nemerosa.ontrack.extension.support.AbstractConfigurationService$decrypt$1.invoke(AbstractConfigurationService.kt:167)
	at net.nemerosa.ontrack.extension.github.model.GitHubEngineConfiguration.decrypt(GitHubEngineConfiguration.kt:114)
	at net.nemerosa.ontrack.extension.github.model.GitHubEngineConfiguration.decrypt(GitHubEngineConfiguration.kt:23)
	at net.nemerosa.ontrack.extension.support.AbstractConfigurationService.decrypt(AbstractConfigurationService.kt:167)
```

**Comment by dcoraboeuf** [comment]
The OAuth2 token used to be non-encrypted and the new version requires it to be encrypted.
