### ISSUE TITLE
Almost works with GitHub Enterprise

### ISSUE THREAD

**Issue by jonbrohauge** [nemerosa/ontrack#916]
Taking OnTrack (v4.0.44) for a spin to see if it is usable with a GitHub Enterprise installation. By customizing the OnTrack Docker Image to include our In-House certificates, it is possible to create a connection to our GHES instance. However it immediately fails with the error message "An error has occurred."
![image](https://user-images.githubusercontent.com/9496731/137271672-db950e6f-824a-43d2-b5c1-b3e7d266bac5.png)

As I understand the exception there is something not quite right in regards to the GraphQL query or the response it gets. I'd like to see if I can possibly find some more details, if you could point me in the right direction as to where to start looking.

I am aware that it is entirely possible that the expected response is not possible, due to the fact that the GraqhQL backend of GHES is not up to date in regards to github.com

Since I'm currently using a test-instance of our GHES (v3.2.0), I am able to try out stuff for you.

This is the exception:

> 2021-10-14 07:24:18.349 DEBUG 1 --- [nio-8080-exec-5] n.n.o.boot.support.LoginSuccessHandler   : Login target URL = http://localhost:8880/
2021-10-14 07:24:21.598  INFO 1 --- [nio-8800-exec-2] o.a.c.c.C.[Tomcat-1].[localhost].[/]     : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-10-14 07:25:38.420 DEBUG 1 --- [nio-8080-exec-6] n.n.o.e.g.client.OntrackGitHubClient     : [github] Gets list of organizations
2021-10-14 07:25:40.413 DEBUG 1 --- [nio-8080-exec-4] n.n.o.e.g.client.OntrackGitHubClient     : [github] Gets list of organizations
2021-10-14 07:25:40.783 DEBUG 1 --- [         task-4] n.n.o.e.g.client.OntrackGitHubClient     : [github] Gets rate limit
2021-10-14 07:25:40.970  WARN 1 --- [         task-4] n.g.e.SimpleDataFetcherExceptionHandler  : Exception while fetching data (/gitHubConfigurations[0]/rateLimits) : {message=Gets rate limit, exception=GitHubErrorMessage(message=Rate limiting is not enabled., errors=null)}

> net.nemerosa.ontrack.extension.github.client.DefaultOntrackGitHubClient$GitHubErrorsException: {message=Gets rate limit, exception=GitHubErrorMessage(message=Rate limiting is not enabled., errors=null)}
        at net.nemerosa.ontrack.extension.github.client.DefaultOntrackGitHubClient.invoke(DefaultOntrackGitHubClient.kt:299)
        at net.nemerosa.ontrack.extension.github.client.DefaultOntrackGitHubClient.getRateLimit(DefaultOntrackGitHubClient.kt:32)
        at net.nemerosa.ontrack.extension.github.ui.graphql.GQLTypeGitHubEngineConfiguration.createType$lambda-1$lambda-0(GQLTypeGitHubEngineConfiguration.kt:58)
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:277)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:202)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74)
        at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:659)
        at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:443)
        at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:538)
        at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:490)
        at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:428)
        at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:393)
        at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:204)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74)
        at graphql.execution.Execution.executeOperation(Execution.java:167)
        at graphql.execution.Execution.execute(Execution.java:108)
        at graphql.GraphQL.execute(GraphQL.java:598)
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:529)
        at graphql.GraphQL.executeAsync(GraphQL.java:493)
        at graphql.GraphQL.execute(GraphQL.java:426)
        at net.nemerosa.ontrack.graphql.service.GraphQLServiceImpl$execute$result$1.invoke(GraphQLServiceImpl.kt:38)
        at net.nemerosa.ontrack.graphql.service.GraphQLServiceImpl$execute$result$1.invoke(GraphQLServiceImpl.kt:37)
        at net.nemerosa.ontrack.tx.TransactionService$DefaultImpls.doInTransaction(TransactionService.kt:12)
        at net.nemerosa.ontrack.tx.DefaultTransactionService.doInTransaction(DefaultTransactionService.kt:9)
        at net.nemerosa.ontrack.graphql.service.GraphQLServiceImpl.execute(GraphQLServiceImpl.kt:37)
        at net.nemerosa.ontrack.graphql.service.GraphQLServiceImpl$$FastClassBySpringCGLIB$$e9dce78f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at net.nemerosa.ontrack.graphql.service.GraphQLServiceImpl$$EnhancerBySpringCGLIB$$4b7950af.execute(<generated>)
        at net.nemerosa.ontrack.graphql.GraphqlController.request(GraphqlController.kt:83)
        at net.nemerosa.ontrack.graphql.GraphqlController.requestAsJson(GraphqlController.kt:74)
        at net.nemerosa.ontrack.graphql.GraphqlController.post$lambda-1(GraphqlController.kt:65)
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:337)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

> 2021-10-14 07:25:41.010 ERROR 1 --- [nio-8080-exec-1] n.n.o.m.support.ApplicationLogService    : [ERROR] name=ui-error,authentication=admin,timestamp=2021-10-14T07:25:40.9950,
Stacktrace: net.nemerosa.ontrack.extension.github.client.DefaultOntrackGitHubClient$GitHubErrorsException: {message=Gets rate limit, exception=GitHubErrorMessage(message=Rate limiting is not enabled., errors=null)}
        at net.nemerosa.ontrack.extension.github.client.DefaultOntrackGitHubClient.invoke(DefaultOntrackGitHubClient.kt:299)
        at net.nemerosa.ontrack.extension.github.client.DefaultOntrackGitHubClient.getRateLimit(DefaultOntrackGitHubClient.kt:32)
        at net.nemerosa.ontrack.extension.github.ui.graphql.GQLTypeGitHubEngineConfiguration.createType$lambda-1$lambda-0(GQLTypeGitHubEngineConfiguration.kt:58)
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:277)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:202)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74)
        at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:659)
        at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:443)
        at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:538)
        at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:490)
        at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:428)
        at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:393)
        at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:204)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74)
        at graphql.execution.Execution.executeOperation(Execution.java:167)
        at graphql.execution.Execution.execute(Execution.java:108)
        at graphql.GraphQL.execute(GraphQL.java:598)
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:529)
        at graphql.GraphQL.executeAsync(GraphQL.java:493)
        at graphql.GraphQL.execute(GraphQL.java:426)
        at net.nemerosa.ontrack.graphql.service.GraphQLServiceImpl$execute$result$1.invoke(GraphQLServiceImpl.kt:38)
        at net.nemerosa.ontrack.graphql.service.GraphQLServiceImpl$execute$result$1.invoke(GraphQLServiceImpl.kt:37)
        at net.nemerosa.ontrack.tx.TransactionService$DefaultImpls.doInTransaction(TransactionService.kt:12)
        at net.nemerosa.ontrack.tx.DefaultTransactionService.doInTransaction(DefaultTransactionService.kt:9)
        at net.nemerosa.ontrack.graphql.service.GraphQLServiceImpl.execute(GraphQLServiceImpl.kt:37)
        at net.nemerosa.ontrack.graphql.service.GraphQLServiceImpl$$FastClassBySpringCGLIB$$e9dce78f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at net.nemerosa.ontrack.graphql.service.GraphQLServiceImpl$$EnhancerBySpringCGLIB$$4b7950af.execute(<generated>)
        at net.nemerosa.ontrack.graphql.GraphqlController.request(GraphqlController.kt:83)
        at net.nemerosa.ontrack.graphql.GraphqlController.requestAsJson(GraphqlController.kt:74)
        at net.nemerosa.ontrack.graphql.GraphqlController.post$lambda-1(GraphqlController.kt:65)
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:337)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by dcoraboeuf** [comment]
@jonbrohauge , any idea how I could test if the rate limits are enabled or not?

**Comment by jonbrohauge** [comment]
As long as your handle the null being returned from the caught exception somewhere, I think it should work.

**Comment by dcoraboeuf** [comment]
Could you please give me an example of GH Enterprise URL, maybe by obfuscating yours?

**Comment by dcoraboeuf** [comment]
@jonbrohauge , 4.0.46 is available with the fix for checking if rate limits are available or not.

**Comment by jonbrohauge** [comment]
So far, so good.
![image](https://user-images.githubusercontent.com/9496731/137450373-61235d72-c8d1-4740-beea-4b1e8e8f243b.png)

Now I need to read on in the docs to sync stuff.

**Comment by jonbrohauge** [comment]
I guess the endpoint has changed during a version upgrade at some point.
I like the concept of this project, so if I can help test on a GHE instance, it's my pleasure. You even get priority over "hacktober" hackathon issues 😉

**Comment by dcoraboeuf** [comment]
The integration tests check only GitHub Cloud, so I'm afraid I'll rely on you for testing against GHE :) But now, all the APIs are aligned with the documentation.

**Comment by dcoraboeuf** [comment]
Available in 4.0.47. @jonbrohauge can I ask you to test with GHE? Thanks

**Comment by jonbrohauge** [comment]
I can see in the log that there are `Catalog entry github::GitHub Enterprise::[Organization]/[Repository]`, and they reflect contents of the Repositories in the Organizations I entered in "Administrator" -> "Settings" -> "GithHub SCM Catalog". I also see the list in Administrator" -> "SCM Catalog".

I have tried to use your Jenkins plugin, and it linked to a project, so so far it works.
If anything new arises while I'm playing around, I'll create a new issue.
