### ISSUE TITLE
GitHub ingestion: tags are still processed

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#963]
```
java.lang.IllegalStateException: Creating branch from tag is not supported: refs/tags/xxx
at net.nemerosa.ontrack.extension.github.ingestion.support.DefaultIngestionModelAccessService.getOrCreateBranch(DefaultIngestionModelAccessService.kt:124)
at net.nemerosa.ontrack.extension.github.ingestion.support.IngestionModelAccessServiceExtensionsKt.getOrCreateBranch(IngestionModelAccessServiceExtensions.kt:11)
at net.nemerosa.ontrack.extension.github.ingestion.processing.config.IngestionPushPayloadListener.process(IngestionPushPayloadListener.kt:24) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.events.PushIngestionEventProcessor.process(PushIngestionEventProcessor.kt:37) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.events.PushIngestionEventProcessor.process(PushIngestionEventProcessor.kt:12) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.AbstractIngestionEventProcessor.process(AbstractIngestionEventProcessor.kt:20) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.DefaultIngestionHookProcessingService.doProcess(DefaultIngestionHookProcessingService.kt:68) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.DefaultIngestionHookProcessingService.access$doProcess(DefaultIngestionHookProcessingService.kt:17) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.DefaultIngestionHookProcessingService$process$1$1.invoke(DefaultIngestionHookProcessingService.kt:35) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.DefaultIngestionHookProcessingService$process$1$1.invoke(DefaultIngestionHookProcessingService.kt:34) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.DefaultIngestionHookProcessingService$process$1.invoke(DefaultIngestionHookProcessingService.kt:34) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.DefaultIngestionHookProcessingService$process$1.invoke(DefaultIngestionHookProcessingService.kt:32) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.DefaultIngestionHookProcessingService.process(DefaultIngestionHookProcessingService.kt:32) 
at net.nemerosa.ontrack.extension.github.ingestion.queue.AsyncIngestionHookQueueListener$onMessage$1.invoke(AsyncIngestionHookQueueListener.kt:84) 
```

That's a follow up on #962 .

On a `push` event containing (redacted):

```
{
   "ref": "refs/tags/xxx",
   "after": "44a",
   "before": "0000000000000000000000000000000000000000",
   "forced": false,
   "pusher": {
   },
   "sender": {
   },
   "commits": [],
   "created": true,
   "deleted": false,
   "base_ref": "refs/heads/main",
   "enterprise": {
   },
   "repository": {
   },
   "head_commit": {
      "id": "44a",
      "added": [],
      "author": {
      },
      "message": "Merge pull request ...",
      "removed": [],
      "tree_id": "...",
      "distinct": true,
      "modified": [
         "...",
      ],
      "committer": {
      },
      "timestamp": "2022-04-27T08:33:28-04:00"
   }
}
```

**Comment by dcoraboeuf** [comment]
Available in 4.1.32
