### ISSUE TITLE
GitHub Ingestion: error when ingestion a tag push event

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#979]
```
java.lang.IllegalStateException: Creating branch from tag is not supported: refs/tags/v0.1.0
at net.nemerosa.ontrack.extension.github.ingestion.support.DefaultIngestionModelAccessService.getOrCreateBranch(DefaultIngestionModelAccessService.kt:129)
at net.nemerosa.ontrack.extension.github.ingestion.support.DefaultIngestionModelAccessService$$EnhancerBySpringCGLIB$$e132bbd4.getOrCreateBranch(<generated>)
at net.nemerosa.ontrack.extension.github.ingestion.support.IngestionModelAccessServiceExtensionsKt.getOrCreateBranch(IngestionModelAccessServiceExtensions.kt:11)
at net.nemerosa.ontrack.extension.github.ingestion.processing.config.IngestionPushPayloadListener.process(IngestionPushPayloadListener.kt:24)
at net.nemerosa.ontrack.extension.github.ingestion.processing.events.PushIngestionEventProcessor.process(PushIngestionEventProcessor.kt:39)
at net.nemerosa.ontrack.extension.github.ingestion.processing.events.PushIngestionEventProcessor.process(PushIngestionEventProcessor.kt:12) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.AbstractIngestionEventProcessor.process(AbstractIngestionEventProcessor.kt:20) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.DefaultIngestionHookProcessingService.doProcess(DefaultIngestionHookProcessingService.kt:68) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.DefaultIngestionHookProcessingService.access$doProcess(DefaultIngestionHookProcessingService.kt:17) 
at net.nemerosa.ontrack.extension.github.ingestion.processing.DefaultIngestionHookProcessingService$process$1$1.invoke(DefaultIngestionHookProcessingService.kt:35)
at net.nemerosa.ontrack.extension.github.ingestion.processing.DefaultIngestionHookProcessingService$process$1$1.invoke(DefaultIngestionHookProcessingService.kt:34) 
...
at net.nemerosa.ontrack.extension.github.ingestion.processing.DefaultIngestionHookProcessingService.process(DefaultIngestionHookProcessingService.kt:32) at 
```

For such a payload:

```json
{
   "ref": "refs/tags/v0.1.0",
}
```

**Comment by dcoraboeuf** [comment]
Available in 4.2.10
